### ISSUE TITLE
Outdated reference to ModuleHandlerInterface?

### ISSUE THREAD

**Issue by wizonesolutions** [socketwench/portingFlagToDrupal8#3]
http://socketwench.github.io/portingFlagToDrupal8/#/12/10

But https://github.com/socketwench/flag-drupal8/blob/5f59ba74254ccf835eeba86c84939a3e47a05bc9/src/FlagService.php **doesn't** seem to inject `ModuleHandlerInterface`?

**Comment by socketwench** [comment]
This reference is indeed outdated. We don't currently implement any hooks in 8.x, although we keep saying we should. The problem is that mentioning hooks is important for the underlying purpose of the presentation. The wording the slide should likely be updated to mention the actually useful bit of information that we _still_ haven't needed to do this.

**Comment by socketwench** [comment]
Updated in the latest version.
